services:
  db:
    image: mysql:8.0
    container_name: jatek-db
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "jatek2025"
    ports:
      - "3307:3307"
    volumes:
      - ./backend/127_0_0_1.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: jatek-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: jatek-frontend
    restart: unless-stopped
    ports:
      - "5090:80"
    depends_on:
      - backend
